version: "3.7"

services:
  database_todo:
    image: postgres
    container_name: database_todo
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: todo
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database_todo
    depends_on: 
      - database_todo

volumes:
  pgdata:
    driver: local